;; -------------------------------------------------------------------
;; clj-fuzzy Double Metaphone Tests
;; -------------------------------------------------------------------
;;
;;
;;   Author: PLIQUE Guillaume (Yomguithereal)
;;   Version: 0.1
;;
(ns clj-fuzzy.double-metaphone-test
  (:require [clojure.test :refer :all]
            [clj-fuzzy.double-metaphone :refer :all]))

(deftest process-test
  (is (= ["SM0" "XMT"] (process "Smith")))
  (is (= ["XMT" "SMT"] (process "Schmidt")))
  (is (= ["TKXN" "TKXN"] (process "dictionary")))
  (is (= ["ANTL" "ANTL"] (process "entelechy")))
  (is (= ["NK" "NK"] (process "knock")))
  (is (= ["RNKL" "RNKL"] (process "wrangler")))
  (is (= ["ALMS" "FLMS"] (process "Williams")))
  (is (= ["AKTN" "AKTN"] (process "Yucatan")))
  (is (= ["HSTK" "HSTK"] (process "haystack")))
  (is (= ["AKSS" "AKSS"] (process "axis")))
  (is (= ["MJR" "MJR"] (process "mujer")))
  (is (= ["TJN" "TJN"] (process "tijuana")))
  (is (= ["AKSN" "AKXN"] (process "Occasionally")))
  (is (= ["ANTT" "ANTT"] (process "antidisestablishmentarianism")))
  (is (= ["APRS" "APRX"] (process "appreciated")))
  (is (= ["PJNN" "PKNN"] (process "beginning")))
  (is (= ["XNJN" "XNKN"] (process "changing")))
  (is (= ["XT" "XT"] (process "cheat")))
  (is (= ["TNJR" "TNKR"] (process "dangerous")))
  (is (= ["TFLP" "TFLP"] (process "development")))
  (is (= ["ATLJ" "ATLK"] (process "etiology")))
  (is (= ["AKSS" "AKSS"] (process "existence")))
  (is (= ["SMPL" "SMPL"] (process "simplicity")))
  (is (= ["SRKM" "SRKM"] (process "circumstances")))
  (is (= ["FR" "FR"] (process "fiery")))
  (is (= ["FPRR" "FPRR"] (process "february")))
  (is (= ["ALJT" "ALKT"] (process "illegitimate")))
  (is (= ["AMTT" "AMTT"] (process "immediately")))
  (is (= ["HPL" "HPL"] (process "happily")))
  (is (= ["JTKM" "ATKM"] (process "judgment")))
  (is (= ["NNK" "NNK"] (process "knowing")))
  (is (= ["KPR" "KPR"] (process "kipper")))
  (is (= ["JN" "AN"] (process "john")))
  (is (= ["LSN" "LXN"] (process "lesion")))
  (is (= ["SF" "SFR"] (process "Xavier")))
  (is (= ["TM" "TM"] (process "dumb")))
  (is (= ["SSR" "SSR"] (process "caesar")))
  (is (= ["KNT" "KNT"] (process "chianti")))
  (is (= ["MKL" "MXL"] (process "michael")))
  (is (= ["KMST" "KMST"] (process "chemistry")))
  (is (= ["KRS" "KRS"] (process "chorus")))
  (is (= ["ARKT" "ARKT"] (process "architect")))
  (is (= ["ARX" "ARK"] (process "arch")))
  (is (= ["ARKS" "ARKS"] (process "orchestra")))
  (is (= ["ARKT" "ARKT"] (process "orchid")))
  (is (= ["AKTL" "FKTL"] (process "wachtler")))
  (is (= ["AKSL" "FKSL"] (process "wechsler")))
  (is (= ["TXNR" "TKNR"] (process "tichner")))
  (is (= ["MK" "MK"] (process "McHugh")))
  (is (= ["SRN" "XRN"] (process "czerny")))
  (is (= ["FKX" "FKX"] (process "focaccia")))
  (is (= ["PLX" "PLX"] (process "bellocchio")))
  (is (= ["PKS" "PKS"] (process "bacchus")))
  (is (= ["AKST" "AKST"] (process "accident")))
  (is (= ["AKST" "AKST"] (process "accede")))
  (is (= ["SKST" "SKST"] (process "succeed")))
  (is (= ["PRTX" "PRTX"] (process "bertucci")))
  (is (= ["MKFR" "MKFR"] (process "mac caffrey")))
  (is (= ["MKRK" "MKRK"] (process "mac gregor")))
  (is (= ["AJ" "AJ"] (process "edge")))
  (is (= ["ATKR" "ATKR"] (process "edgar")))
  (is (= ["JLN" "JLN"] (process "ghislane")))
  (is (= ["JRTL" "JRTL"] (process "ghiradelli")))
  (is (= ["H" "H"] (process "hugh")))
  (is (= ["P" "P"] (process "bough")))
  (is (= ["PRTN" "PRTN"] (process "broughton")))
  (is (= ["LF" "LF"] (process "laugh")))
  (is (= ["MKLF" "MKLF"] (process "McLaughlin")))
  (is (= ["KF" "KF"] (process "cough")))
  (is (= ["KF" "KF"] (process "gough")))
  (is (= ["RF" "RF"] (process "rough")))
  (is (= ["TF" "TF"] (process "tough")))
  (is (= ["KKN" "KKN"] (process "cagney")))
  (is (= ["TKLR" "TLR"] (process "tagliaro")))
  (is (= ["PJ" "PK"] (process "biaggi")))
  (is (= ["SNHS" "SNHS"] (process "san jacinto")))
  (is (= ["ANKL" "ANKL"] (process "Yankelovich")))
  (is (= ["JNKL" "ANKL"] (process "Jankelowicz")))
  (is (= ["PJTR" "PHTR"] (process "bajador")))
  (is (= ["KPRL" "KPR"] (process "cabrillo")))
  (is (= ["KLKS" "KKS"] (process "gallegos")))
  (is (= ["TM" "TM"] (process "dumb")))
  (is (= ["0M" "TM"] (process "thumb")))
  (is (= ["KMPL" "KMPL"] (process "campbell")))
  (is (= ["RSPR" "RSPR"] (process "raspberry")))
  (is (= ["HKMR" "HKMR"] (process "hochmeier")))
  (is (= ["ALNT" "ALNT"] (process "island")))
  (is (= ["AL" "AL"] (process "isle")))
  (is (= ["KRLL" "KRLL"] (process "carlisle")))
  (is (= ["KRLL" "KRLL"] (process "carlysle")))
  (is (= ["SNTR" "XNTR"] (process "snider")))
  (is (= ["XNTR" "SNTR"] (process "schneider")))
  (is (= ["SKL" "SKL"] (process "school")))
  (is (= ["SKNR" "SKNR"] (process "schooner")))
  (is (= ["XRMR" "SKRM"] (process "schermerhorn")))
  (is (= ["XNKR" "SKNK"] (process "schenker")))
  (is (= ["RSN" "RSNS"] (process "resnais")))
  (is (= ["ART" "ARTS"] (process "artois")))
  (is (= ["TMS" "TMS"] (process "thomas")))
  (is (= ["ASRM" "FSRM"] (process "Wasserman")))
  (is (= ["FSRM" "FSRM"] (process "Vasserman")))
  (is (= ["AM" "AM"] (process "Uomo")))
  (is (= ["AM" "FM"] (process "Womo")))
  (is (= ["ARN" "ARNF"] (process "Arnow")))
  (is (= ["ARNF" "ARNF"] (process "Arnoff")))
  (is (= ["FLPT" "FLPF"] (process "filipowicz")))
  (is (= ["PR" "PR"] (process "breaux")))
  (is (= ["J" "J"] (process "zhao")))
  (is (= ["TMS" "TMS"] (process "thames"))))
