;; -------------------------------------------------------------------
;; clj-fuzzy Double Metaphone Tests
;; -------------------------------------------------------------------
;;
;;
;;   Author: PLIQUE Guillaume (Yomguithereal)
;;   Version: 0.1
;;
(ns clj-fuzzy.double-metaphone-test
  (:require [clojure.test :refer :all]
            [clj-fuzzy.double-metaphone :refer :all]))

(deftest process-test
  (is (= ["SM0" "XMT"] (process "Smith")))
  (is (= ["TKXN" "TKXN"] (process "dictionnary")))
  (is (= ["ANTL" "ANTL"] (process "entelechy")))
  (is (= ["NK" "NK"] (process "knock")))
  (is (= ["RNKL" "RNKL"] (process "wrangler")))
  (is (= ["ALMS" "FLMS"] (process "Williams")))
  (is (= ["AKTN" "AKTN"] (process "Yucatan")))
  (is (= ["HSTK" "HSTK"] (process "haystack")))
  (is (= ["AKSS" "AKSS"] (process "axis")))
  (is (= ["MJR" "MJR"] (process "mujer")))
  (is (= ["TJN" "TJN"] (process "tijuana")))
  (is (= ["AKSN" "AKXN"] (process "Occasionally")))
  (is (= ["ANTT" "ANTT"] (process "antidisestablishmentarianism")))
  (is (= ["APRS" "APRX"] (process "appreciated")))
  (is (= ["PJNN" "PKNN"] (process "beginning")))
  (is (= ["XNJN" "XNKN"] (process "changing")))
  (is (= ["XT" "XT"] (process "cheat")))
  (is (= ["TNJR" "TNKR"] (process "dangerous")))
  (is (= ["TFLP" "TFLP"] (process "development")))
  (is (= ["ATLJ" "ATLK"] (process "etiology")))
  (is (= ["AKSS" "AKSS"] (process "existence")))
  (is (= ["SMPL" "SMPL"] (process "simplicity")))
  (is (= ["SRKM" "SRKM"] (process "circumstances")))
  (is (= ["FR" "FR"] (process "fiery")))
  (is (= ["FPRR" "FPRR"] (process "february")))
  (is (= ["ALJT" "ALKT"] (process "illegitimate")))
  (is (= ["AMTT" "AMTT"] (process "immediately")))
  (is (= ["HPL" "HPL"] (process "happily")))
  (is (= ["JTKM" "ATKM"] (process "judgment")))
  (is (= ["NNK" "NNK"] (process "knowing")))
  (is (= ["KPR" "KPR"] (process "kipper")))
  (is (= ["JN" "AN"] (process "john")))
  (is (= ["LSN" "LXN"] (process "lesion")))
  (is (= ["SF" "SFR"] (process "Xavier")))
  (is (= ["TM" "TM"] (process "dumb")))
  (is (= ["SSR" "SSR"] (process "caesar")))
  (is (= ["KNT" "KNT"] (process "chianti")))
  (is (= ["MKL" "MXL"] (process "michael")))
  (is (= ["KMST" "KMST"] (process "chemistry")))
  (is (= ["KRS" "KRS"] (process "chorus")))
  (is (= ["ARKT" "ARKT"] (process "architect")))
  (is (= ["ARX" "ARK"] (process "arch")))
  (is (= ["ARKS" "ARKS"] (process "orchestra")))
  (is (= ["ARKT" "ARKT"] (process "orchid")))
  (is (= ["AKTL" "FKTL"] (process "wachtler")))
  (is (= ["AKSL" "FKSL"] (process "wechsler")))
  (is (= ["TXNR" "TKNR"] (process "tichner")))
  (is (= ["MK" "MK"] (process "McHugh")))
  (is (= ["SRN" "XRN"] (process "czerny")))
  (is (= ["FKX" "FKX"] (process "focaccia")))
  (is (= ["PLX" "PLX"] (process "bellocchio")))
  (is (= ["PKS" "PKS"] (process "bacchus")))
  (is (= ["AKST" "AKST"] (process "accident")))
  (is (= ["AKST" "AKST"] (process "accede")))
  (is (= ["SKST" "SKST"] (process "succeed")))
  (is (= ["PRTX" "PRTX"] (process "bertucci")))

  (is (= ["MKRK" "MKRK"] (process "mac gregor")))
  (is (= ["PJTR" "PHTR"] (process "bajador"))))
